<a href="https://colab.research.google.com/github/olooyasir-cmd/Machine-learning-proj./blob/main/Yasir_Abdul_Rahaman_Python_practical_Assignment_student_version_(1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Python Practical Assisgnment






## Instructions to students
* **DO NOT ADD / REMOVE CELLS FROM THIS NOTEBOOK, AND DO NOT CHANGE THE NAMES OF THE FUNCTIONS REQUIRED FOR TESTING.**
  
* This Assignment consists of 5 questions. Each of the questions is independent and do not require you to use functions built from previous questions. You can answer the questions in any order you like.

* Ensure that the answers to your questions do not contain `syntax` or `indentation` errors. Questions with these errors will break the auto grader and will mark the _**entire Assisgnment**_ as incorrect.
* Only place code in sections that contain the `# Your code here.` comment.
* We have provided some expected outputs for your code. Use these to determine if your code behaves as intended.
* Some questions may have multiple requirements.

FULL NAME: YASIR ABDUL-RAHAMAN

EMAIL:abdulrahamanyasir81@gmail.com





In [1]:
import numpy as np
import pandas as pd

## Section 1: Numerical computation
### Question 1
We have a rope and want to cut the rope into four pieces to make a square. Given a rope of length $x$, what is the largest square (by area) that can be built given that a side of the square, $s$, can only be integer values? Units of measurement can be ignored. We are only interested in the numerical value of the solution.
<p align="center">
<img src="https://raw.githubusercontent.com/Explore-AI/Pictures/master/python_fundamentals/python_exam/Largest_Square_Rope.jpg"
     alt="Largest Square"
     style="float: center; padding-bottom=0.5em"
     width=700px/>
     <br>
     <em>Figure 1: Area of the largest square enclosed by a rope. </em>
</p>    

**Function specifications**

*Argument(s):*

- **x** `(float)` $\rightarrow$ the length of the rope.

*Return:*

- **area** `(int)` $\rightarrow$ the area of the square formed by the rope.

> 💡**HINT**💡
>
>The perimeter of the square cannot exceed the length of the rope.

In [2]:
### START FUNCTION
def largest_square(x):
    # Your code here.
    s = int(x // 4)
    area = s ** 2
    return area
### END FUNCTION

In [3]:
largest_square(41.5)

100

In [4]:
print(largest_square(324))

6561


_**Expected outputs:**_
```python
largest_square(12) == 9
largest_square(41.5) == 100
largest_square(324) == 6561
```

### Question 2
Given a square matrix of size $n\times n $ that only contains integers, compute the sum of the two diagonals. If the dimension of the square matrix is odd, make sure that you are not double-counting the value at the centre of the matrix.

<p align="center">
<img src="https://raw.githubusercontent.com/Explore-AI/Pictures/master/python_fundamentals/python_exam/Sum_of_diagonals.jpg"
     alt="Sum of diagonals"
     style="float: center; padding-bottom=0.5em"
     width=50%/>
     <br>
     <em>Figure 2: Sum of diagonals.</em>
</p>    


**Function specifications**

*Arguments:*
- **matrix** `(numpy.ndarray)` $\rightarrow$ input matrix to be used for computing the sum.

*Return:*
- **sum** `(int)` $\rightarrow$  return the sum of the two diagonals.


In [5]:
### START FUNCTION
def sum_of_diagonals(matrix):
    # Your code here.
    n = matrix.shape[0]
    total = 0

    for i in range(n):
        total += matrix[i][i]
        total += matrix[i][n - 1 - i]

    if n % 2 == 1:
        total -= matrix[n // 2][n // 2]

    return int(total)
### END FUNCTION

In [6]:
matrix =np.random.randint(10,size=(4,4))
print(matrix)
sum_of_diagonals(matrix)

[[8 7 8 5]
 [4 0 0 8]
 [0 5 3 2]
 [1 0 4 2]]


24

_**Expected outputs:**_
```python
matrix = np.array([[7, 0, 8],
                   [6, 9, 1],
                   [3, 8, 4]])
sum_of_diagonals(matrix)==31


matrix = np.array([[4, 1, 1, 1],
                   [1, 3, 8, 0],
                   [0, 8, 5, 7],
                   [1, 6, 1, 3]])
sum_of_diagonals(matrix)==33
```

## Section 2: Strings and lists

### Question 3:

Write a function that computes the ratio of vowels vs. consonants ($\frac{vowels}{consonants}$) in a given sentence. The ratio should be given as a floating-point number rounded off to two decimal places. When writing your function, be sure to appropriately cater for the following punctuation marks:
- apostrophes (')
- quotations (")
- full stops (.)
- commas (,)
- exclamations (!)  
- question marks (?)
- colons (:)
- semicolons (;)

*Arguments:*
- **sentence** `(string)` $\rightarrow$ sentence required to compute the ratio.

*Return:*
- **ratio** `(float)` $\rightarrow$ a ratio that describes the number of vowels to consonants: vowels/consonants.

> 💡**HINT**💡
>
>Remember to cater for the white spaces that appear in your sentence.

In [7]:
### START FUNCTION
def vowel_consonant_ratio(sentence):
    # Your code here.
    vowels = set('aeiouAEIOU')
    vowel_count = 0
    consonant_count = 0

    for char in sentence:
        if char.isalpha():
          if char in vowels:
            vowel_count += 1
          else:
            consonant_count += 1

    if consonant_count == 0:
        return 0.0

    ratio = vowel_count / consonant_count
    ratio = round(ratio, 2)

    return ratio
### END FUNCTION

In [8]:
vowel_consonant_ratio("Thomas! Where have you been?")

0.83

In [9]:
vowel_consonant_ratio("Thomas! Where have you been?")==0.83

True

***Expected outputs***

```python
vowel_consonant_ratio("This is a random sentence!")==0.62
vowel_consonant_ratio("Thomas! Where have you been?")==0.83
```

### Question 4

Write a function that will redact every third word in a sentence. Make use of the hashtag (`#`) symbol to redact the characters that make up the word, i.e. if the word is five characters long then a string of five hashtags should replace that word. However, this should not redact any of the following punctuation marks:
- apostrophes (')
- quotations (")
- full stops (.)
- commas (,)
- exclamations (!)  
- question marks (?)
- colons (:)
- semicolons (;)

*Arguments:*
- **sentence** `(string)` $\rightarrow$ sentence that needs to be redacted.

*Return:*
- **redacted sentence** `(string)`$\rightarrow$ every third word should be redacted.

In [10]:
### START FUNCTION
def redact_words(sentence):
    # Your code here.
    words = sentence.split()
    redacted_words = []

    punctuation = "'\". , ! ? : ;".split()

    for i, word in enumerate(words, 1):

        if i % 3 == 0:
            redacted_word = ""
            for char in word:

                if char in punctuation:
                    redacted_word += char
                else:

                    redacted_word += "#"
            redacted_words.append(redacted_word)
        else:

            redacted_words.append(word)


    return " ".join(redacted_words)
### END FUNCTION

In [11]:
sentence = "Explorer, this is why you shouldn't come to a test unprepared."
redact_words(sentence)

'Explorer, this ## why you ######### come to # test unprepared.'

In [12]:
sentence = "My dear Explorer, do you understand the nature of the given question?"
redact_words(sentence)

'My dear ########, do you ########## the nature ## the given ########?'

***Expected outputs***

```python
sentence = "My dear Explorer, do you understand the nature of the given question?"
redact_words(sentence) ==  'My dear ########, do you ########## the nature ## the given ########?'

sentence = "Explorer, this is why you shouldn't come to a test unprepared."
redact_words(sentence)=="Explorer, this ## why you #######'# come to # test unprepared."

```

### Question 5

Given an alphanumeric list, separate it into three different lists stored in a dictionary:

- The first list should only contain lowercase letters.
- The second list should only contain uppercase letters.
- The third list should only contain numbers.

Each list stored in the dictionary should be stored in ascending order. Use the following naming convention when creating your lists:
- numbers
- uppercase
- lowercase

Make sure that you adhere to the above instruction, as the name of your lists will be used to mark your function.

*Arguments:*
- **character_list:** `(list)` $\rightarrow$ list of alphanumeric characters.

*Return:*
- **dictionary** `(dict)` $\rightarrow$  dictionary containing all three lists.

In [13]:
### START FUNCTION
def create_dictionary(character_list):
    # Your code here.
    lowercase = []
    uppercase = []
    numbers = []

    for char in character_list:

      char_str = str(char)

      if char_str.isdigit():
        numbers.append(char)
      elif char_str.islower():
        lowercase.append(char)
      elif char_str.isupper():
        uppercase.append(char)

    numbers.sort()
    uppercase.sort()
    lowercase.sort()

    resul_dictionary = {
        'numbers': numbers,
        'uppercase': uppercase,
        'lowercase': lowercase
    }

    return resul_dictionary
### END FUNCTION

In [14]:
lst = [2,'j','K','o',6,'x',5,'A',3.2]
create_dictionary(lst)

{'numbers': [2, 5, 6], 'uppercase': ['A', 'K'], 'lowercase': ['j', 'o', 'x']}

In [15]:
lst = [2,'j','K','o',6,'x',5,'A',3.2]
create_dictionary(lst)

{'numbers': [2, 5, 6], 'uppercase': ['A', 'K'], 'lowercase': ['j', 'o', 'x']}

***Expected outputs***

```python
lst = [2,'j','K','o',6,'x',5,'A',3.2]
create_dictionary(lst)

{'numbers': [2, 3.2, 5, 6],
 'uppercase': ['A', 'K'],
 'lowercase': ['j', 'o', 'x']}
 ```

